### PR TITLE
Representations now use molecule class.

### PR DESCRIPTION
**Pull request by shivupa**
Molecule class need to be slightly modified to allow use to "overload" the constructor.
We can call a null constructor and just make the molecule the instantiate.
Or we can call the constructor with a filename and it will create and instatiate the molecule.

Both representations now use the molecule class. Previous the code checked if the file was
of a supported type before making the rep. This has been removed. I think that this should be
handled by the molecule class followed by a try,except,pass. I will open an issue for discussion
and we should probably discuss in person as well.

### CODE REVIEW

**Comment by dlf57** [comment]
Should we start adding __init__.py to initialize so that we are then just importing by 
```python
from .utils/molecule import Molecule
``` 
Instead of importing sys and using path.append?

**Comment by dlf57** [comment]
For the coulomb_matrix.py:
```python
if current_molecule.n_atom > size:
    raise Exception(
        'Molecule has {} atoms. Increase matrix size.'.format(n_atom))
```
Do we need to have ```n_atom``` be ```current_molecule.n_atom```?

**Comment by shivupa** [comment]
I changed the imports to `from utils.molecule import Molecule` which worked. I haven't done the init.py stuff before so I decided that it would be nice if we could save that for issue #9

**Comment by dlf57** [comment]
Everything looks good. I can work on #9 and #3 later this week

**Pull request merged**
